routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
    DB::listen(function($query){
        echo "<pre>{$query->sql}</pre>";
    });
*/


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('carros', 'CarroController');
Route::resource('concesionarios', 'ConcesionarioController');

app/Carro.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Carro extends Model
{

    // Atributos

    protected $fillable = [
        'nombre',
        'placa',
        'modelo',
        'concesionario_id'
    ];

    // protected $guard = [
    //     ''
    // ];

    // Muteadores

        // Getters

        // Setters
        
    // Relaciones

    public function Concesionario()
    {
        return $this->belongsTo(Concesionario::class);
    }

    // Metodos
}

app/Concesionario.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Concesionario extends Model
{
    protected $fillable = [

        'nombre'
        
    ];

    // Muteadores

        // Getters

        // Setters
        
    // Relaciones

    public function Carros()
    {
        return $this->hasMany(Carro::class);
    }

    // Metodos
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/CarroController.php
<?php

namespace App\Http\Controllers;

use App\Carro;
use App\Concesionario;
use Illuminate\Http\Request;

class CarroController extends Controller
{
   
    public function index()
    {
        
        $listaCarros =  Carro::with('Concesionario')->get();
        return view('carros.index', compact('listaCarros')); // array asociativo [listaCarros => $listaCarros]
    }

    
    public function create()
    {
        $listaConcecionarios = Concesionario::all();
      
        return view('carros.create',compact('listaConcecionarios'));
    }

    
    public function store(Request $request)
    {

        //$carro = Carro::create($request->all());
    
        $carro = Carro::create([
            'nombre' => $request->nombre,
            'placa' => $request->placa,
            'modelo' => $request->modelo,
            'concesionario_id' => $request->concesionario_id
        ]);

        return redirect()->route('carros.index')->with('success', 'Se registró el carro de forma exitosa');
    }

    public function show(Carro $carro)
    {
        return view('carros.show', compact('carro'));
    }

    
    public function edit(Carro $carro)
    {
        $listaConcecionarios = Concesionario::all();
        return view('carros.edit', compact('carro', 'listaConcecionarios'));
    }

   
    public function update(Request $request, Carro $carro)
    {
        $carro->update($request->all());
        return redirect()->route('carros.index')->with('success', 'Se actualizó el carro de forma exitosa');
    }

   
    public function destroy(Carro $carro)
    {
        $carro->delete();
        return redirect()->back()->with('success', 'Se eliminó el carro de forma exitosa');
    }
}

app/Http/Controllers/ConcesionarioController.php
<?php

namespace App\Http\Controllers;

use App\Concesionario;
use App\Carro;
use Illuminate\Http\Request;

class ConcesionarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {        
        $concesionarios = Concesionario::with('Carros')->get();        
        return view('concesionario.index', compact('concesionarios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('concesionario.create');
    }

    public function store(Request $request)
    {
        $concesionario = Concesionario::create([
            'nombre' => $request->nombre,
        ]);

        return redirect()->route('concesionarios.index')->with('success', 'Se registró el concesionario de forma exitosa');
    }

    public function show(Concesionario $concesionario)
    {
        $listaCarros = Carro::where("concesionario_id", $concesionario->id)->get();
        return view('concesionario.show', compact('concesionario','listaCarros'));
    }


    public function edit(Concesionario $concesionario)
    {
        return view('concesionario.edit', compact('concesionario'));
    }

    public function update(Request $request, Concesionario $concesionario)
    {
        $concesionario->update($request->all());
        return redirect()->route('concesionarios.index')->with('success', 'Se actualizó el concesionario de forma exitosa');
    }

 
    public function destroy(Concesionario $item)
    {
        dd($item);
        
        //$item->delete();
        //return redirect()->back()->with('success', 'Se eliminó el concesionario de forma exitosa');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/carros/create.blade.php
@extends('layouts.app')

@section('contenido')
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6">
                <h1 class="text-center">¡Registra tu Carro!</h1>
                <form action="{{route('carros.store')}}" method="POST" class="form-group">

                        @csrf
                        <label for="nombre">Nombre</label>
                        <input type="text"  class="form-control" value="" id="nombre" name="nombre">
                        <label for="placa">Placa</label>
                        <input type="text"  class="form-control" value="" id="placa" name="placa">
                        <label for="modelo">Modelo</label>
                        <input type="number"  min="2000" max="2020" class="form-control" value="" id="modelo" name="modelo">
                        <label for="concesionario_id">Concesionario</label>
                        <select class="form-control" name="concesionario_id" id="concesionario_id">
                            @foreach ($listaConcecionarios as $item)
                                <option value="{{$item->id}}">{{$item->nombre}}</option>
                            @endforeach
                        </select>
                        <input type="submit" value="Registrar" class="mt-4 btn btn-block btn-primary">
                </form>
                <a class="d-flex justify-content-center" href="{{route('carros.index')}}">Volver</a>
            </div>
        </div>
    </div>
@endsection

resources/views/carros/deleteModal.blade.php
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Eliminar {{$carro->nombre}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>¿Está seguro de eliminar este carro?</p>
                <p><small>Un carro despues de ser eliminado no se puede recuperar</small></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <form action="{{ route('carros.destroy', $carro) }}" method="post">
                    @csrf @method('DELETE')
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                </form>                        
            </div>
        </div>
    </div>
</div>

resources/views/carros/edit.blade.php
@extends('layouts.app')

@section('contenido')
<div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6">
                <form action="{{route('carros.update', $carro)}}" method="POST" class="form-group">

                        @csrf  @method("PUT")
                        <label for="nombre">Nombre</label>
                        <input type="text"  class="form-control" value="{{$carro->nombre}}" id="nombre" name="nombre">
                        <label for="placa">Placa</label>
                        <input type="text"  class="form-control" value="{{$carro->placa}}" id="placa" name="placa">
                        <label for="modelo">Modelo</label>
                        <input type="number"  min="2000" max="2020" class="form-control" value="{{$carro->modelo}}" id="modelo" name="modelo">
                        <label for="concesionario_id">Concesionario</label>
                        <select class="form-control" value="{{$carro->concesionario_id}}" name="concesionario_id" id="concesionario_id">
                            @foreach ($listaConcecionarios as $item)
                                <option value="{{$item->id}}">{{$item->nombre}}</option>
                            @endforeach
                        </select>
                        

                        <input type="submit" value="Guardar" class="mt-4 btn btn-block btn-success">
                </form>
            </div>
        </div>
</div>
@endsection

resources/views/carros/index.blade.php
@extends('layouts.app')

@section('contenido')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
             
                <h1 class="text-center">Listado de Carros</h1>
                
                @auth
                <a class="float-right btn btn-primary my-2" href="{{route('carros.create')}}"><i class="fas fa-plus"></i></a>
                @endauth
                
                    @if (Session::has('success'))
                        <div id="mensaje">
                            <div class="alert alert-success text-center">{{Session::get('success')}}</div>
                        </div>
                    @endif
                
                <table class="table table-striped">
                    <thead class="thead-dark">
                        <tr>
                            <th width="15px">Id</th>
                            <th>Nombre</th>
                            <th>Placa</th>
                            <th>Modelo</th>
                            <th>Concesionario</th>                       
                            <th width="200px">Acciones</th>                                                        
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($listaCarros as $carro)
                        <tr>
                            <th>{{$carro->id}}</th>
                            <td>{{$carro->nombre}}</td>
                            <td>{{$carro->placa}}</td>
                            <td>{{$carro->modelo}}</td>
                            <td>
                                {{$carro->Concesionario->nombre}}
                            </td>
                            <td>
                                <a href="{{route('carros.show', $carro)}}" class="btn btn-info"><i class="far fa-eye"></i></a>
                                @auth
                                    <a href="{{route('carros.edit', $carro)}}" class="btn btn-success"><i class="far fa-edit"></i></a>
                                    <a href="{{route('carros.destroy', $carro)}}" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal"><i class="far fa-trash-alt"></i></a>
                                    @include('carros.deleteModal')  
                                @endauth
                                                             
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('mis-scripts')
    <script src="{{ asset('js/myApp.js') }}"></script>
@endpush

resources/views/carros/show.blade.php
@extends('layouts.app')

@section('contenido')
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body text-center">
                        <p><b>Nombre:</b> {{$carro->nombre}}</p>
                        <p><b>Placa:</b> {{$carro->placa}}</p>
                        <p><b>Modelo:</b> {{$carro->modelo}}</p>
                        <p><b>Concesionario:</b> {{$carro->Concesionario->nombre}}</p>
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-block btn-success" href="{{route('carros.index')}}">Volver.</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/concesionario/create.blade.php
@extends('layouts.app')

@section('contenido')
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6">
                <h1 class="text-center">¡Registra tu Concesionario!</h1>
                <form action="{{route('concesionarios.store')}}" method="POST" class="form-group">

                        @csrf
                        <label for="nombre">Nombre</label>
                        <input type="text"  class="form-control" value="" id="nombre" name="nombre">

                        <input type="submit" value="Registrar" class="mt-4 btn btn-block btn-primary">
                </form>
                <a class="d-flex justify-content-center" href="{{route('concesionarios.index')}}">Volver</a>
            </div>
        </div>
    </div>
@endsection

resources/views/concesionario/deleteModal.blade.php
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Eliminar {{$item->nombre}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>¿Está seguro de eliminar este Concesionario?</p>
                    <p><small>Un concesionario despues de ser eliminado no se puede recuperar</small></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <form action="{{ route('concesionarios.destroy', $item) }}" method="post">
                        @csrf @method('DELETE')
                        <button type="submit" class="btn btn-danger">Eliminar</button>
                    </form>                        
                </div>
            </div>
        </div>
    </div>

resources/views/concesionario/edit.blade.php
@extends('layouts.app')

@section('contenido')
<div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6">
                <form action="{{route('concesionarios.update', $concesionario)}}" method="POST" class="form-group">

                        @csrf  @method("PUT")
                        <label for="nombre">Nombre</label>
                        <input type="text"  class="form-control" value="{{$concesionario->nombre}}" id="nombre" name="nombre">
                        <input type="submit" value="Guardar" class="mt-4 btn btn-block btn-success">
                </form>
            </div>
        </div>
</div>
@endsection

resources/views/concesionario/index.blade.php
@extends('layouts.app')

@section('contenido')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center">Listado de Concesionarios</h1>
            <a class="float-right btn btn-primary my-2" href="{{route('concesionarios.create')}}"><i class="fas fa-plus"></i></a>
                
                    @if (Session::has('success'))
                        <div id="mensaje">
                            <div class="alert alert-success text-center">{{Session::get('success')}}</div>
                        </div>
                    @endif
                
                <table class="table table-striped">
                    <thead class="thead-dark text-center">
                        <tr>
                            <th width="15px">Id</th>
                            <th width="250px">Nombre</th>
                            <th width="200px">Acciones</th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                        @foreach ($concesionarios as $item)
                        <tr>
                            <th>{{$item->id}}</th>
                            <td>{{$item->nombre}}</td>
                            <td>
                                <a href="{{route('concesionarios.show', $item)}}" class="btn btn-info"><i class="far fa-eye"></i></a>
                                <a href="{{route('concesionarios.edit', $item)}}" class="btn btn-success"><i class="far fa-edit"></i></a> 
                                <a href="#" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal"><i class="far fa-trash-alt"></i></a>
                                @include('concesionario.deleteModal')                                
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('mis-scripts')
    <script src="{{ asset('js/myApp.js')}}"></script>
@endpush

resources/views/concesionario/show.blade.php
@extends('layouts.app')

@section('contenido')
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body text-center">
                        <h3>¡Concesionario <b>{{$concesionario->nombre}}</b>!</h3>
                        <hr>
                        <div class="text-left">
                            <ul>
                                @if (count($listaCarros) <= 0)
                                    <p class="text-center">No hay carros en este concesionario.</p>
                                @else
                                    @foreach ($listaCarros as $item)
                                        <li>{{$item->nombre}}</li>
                                    @endforeach
                                @endif
                                
                            </ul>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-block btn-success" href="{{route('concesionarios.index')}}">Volver.</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="https://kit.fontawesome.com/16f4674b0c.js" crossorigin="anonymous"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('contenido')
        </main>
    </div>

    @stack('mis-scripts')
</body>
</html>